language: scala

scala:
   - 2.10.10
   - 2.13.1
   
jdk:
  - oraclejdk8
  - oraclejdk12
  - openjdk12

install:
  - pip install --user codecov
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.8.5
