name: ShEx-Lite Test Linux Platform

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
        architecture: x64
    - name: Run tests
      run: sbt ++2.13.1! clean test
